name = "vmware-tool"
compatibility_date = "2023-10-30"
pages_build_output_dir = "."
type = "javascript"
account_id = ""
workers_dev = true
route = ""
zone_id = ""

[build]
command = "npm install"
dir = "."

[vars]
NODE_VERSION = "18"

[build.upload]
format = "service-worker"

[dev]
port = 3000
local_protocol = "http"